import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Kanit } from 'next/font/google'
import '../../scss/globals.scss'
import Layout from '@/components/layout'

const kanit = Kanit({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={kanit.className}>
          <Layout>{children}</Layout>
        </body>
      </html>
    </ClerkProvider>
  )
}
